/**
 * @qwickapps/server
 *
 * Independent control panel and management UI for QwickApps services
 * Runs on a separate port, provides health checks, logs, config, and diagnostics
 *
 * Copyright (c) 2025 QwickApps.com. All rights reserved.
 */

// Core exports
export { createControlPanel } from './core/control-panel.js';
export type { CreateControlPanelOptions } from './core/control-panel.js';
export { createGateway } from './core/gateway.js';
export { HealthManager } from './core/health-manager.js';

// Plugin Registry exports (event-driven architecture v2.0)
export {
  createPluginRegistry,
  getPluginRegistry,
  hasPluginRegistry,
  resetPluginRegistry,
  PluginRegistryImpl,
} from './core/plugin-registry.js';
export type {
  Plugin,
  PluginConfig,
  PluginEvent,
  PluginEventHandler,
  PluginRegistry,
  PluginInfo,
  MenuContribution,
  PageContribution,
  WidgetContribution,
  RouteDefinition,
} from './core/plugin-registry.js';

// Route guards (for control panel protection)
export { createRouteGuard } from './core/guards.js';

// Logging exports
export {
  initializeLogging,
  getControlPanelLogger,
  getLoggingSubsystem,
} from './core/logging.js';
export type { LoggingConfig } from './core/logging.js';

export type {
  ControlPanelConfig,
  ControlPanelInstance,
  HealthCheck,
  HealthCheckType,
  HealthCheckResult,
  HealthStatus,
  LogSource,
  ConfigDisplayOptions,
  Logger,
  DiagnosticsReport,
  // Route guard types
  RouteGuardType,
  RouteGuardConfig,
  BasicAuthGuardConfig,
  SupabaseAuthGuardConfig,
  Auth0GuardConfig,
  NoAuthGuardConfig,
  MountConfig,
  FrontendAppConfig,
} from './core/types.js';
export type {
  GatewayConfig,
  GatewayInstance,
  MountedAppConfig,
} from './core/gateway.js';

// Built-in plugins
export {
  createHealthPlugin,
  createLogsPlugin,
  createConfigPlugin,
  createDiagnosticsPlugin,
  createFrontendAppPlugin,
  // Postgres plugin
  createPostgresPlugin,
  getPostgres,
  hasPostgres,
  // Cache plugin
  createCachePlugin,
  getCache,
  hasCache,
  // Auth plugin
  createAuthPlugin,
  createAuthPluginFromEnv,
  getAuthStatus,
  setAuthConfigStore,
  postgresAuthConfigStore,
  isAuthenticated,
  getAuthenticatedUser,
  getAccessToken,
  requireAuth,
  requireRoles,
  requireAnyRole,
  auth0Adapter,
  basicAdapter,
  supabaseAdapter,
  supertokensAdapter,
  isAuthenticatedRequest,
  // Users plugin
  createUsersPlugin,
  getUserStore,
  getUserById,
  getUserByEmail,
  findOrCreateUser,
  postgresUserStore,
  // Bans plugin (separate from Users, depends on Users)
  createBansPlugin,
  getBanStore,
  isUserBanned,
  isEmailBanned,
  getActiveBan,
  banUser,
  unbanUser,
  listActiveBans,
  postgresBanStore,
  // Entitlements plugin
  createEntitlementsPlugin,
  getEntitlementSource,
  isSourceReadonly,
  getEntitlements,
  refreshEntitlements,
  hasEntitlement,
  hasAnyEntitlement,
  hasAllEntitlements,
  grantEntitlement,
  revokeEntitlement,
  setEntitlements,
  getAvailableEntitlements,
  getEntitlementStats,
  invalidateEntitlementCache,
  storeExternalIdMapping,
  invalidateByExternalId,
  requireEntitlement,
  requireAnyEntitlement,
  requireAllEntitlements,
  postgresEntitlementSource,
  // Rate Limit plugin
  createRateLimitPlugin,
  createRateLimitPluginFromEnv,
  getRateLimitConfigStatus,
  postgresRateLimitStore,
  createRateLimitCache,
  createNoOpCache,
  createSlidingWindowStrategy,
  createFixedWindowStrategy,
  createTokenBucketStrategy,
  getStrategy,
  rateLimitMiddleware,
  rateLimitStatusMiddleware,
  RateLimitService,
  getRateLimitService,
  isLimited,
  checkLimit,
  incrementLimit,
  getRemainingRequests,
  getLimitStatus,
  clearLimit,
  createCleanupJob,
  // Devices plugin
  createDevicesPlugin,
  getDeviceStore,
  getDeviceAdapter,
  registerDevice,
  verifyDeviceToken,
  getDeviceById,
  updateDevice,
  deleteDevice,
  regenerateToken,
  listUserDevices,
  listOrgDevices,
  deactivateDevice,
  activateDevice,
  cleanupExpiredTokens,
  postgresDeviceStore,
  computeDeviceAdapter,
  mobileDeviceAdapter,
  generateDeviceToken,
  generatePairingCode,
  hashToken,
  verifyToken,
  isValidTokenFormat,
  isTokenExpired,
  getTokenExpiration,
  DeviceTokens,
  // Profiles plugin
  createProfilesPlugin,
  getProfileStore,
  createProfile,
  getProfileById,
  updateProfile,
  deleteProfile,
  listUserProfiles,
  getDefaultProfile,
  setDefaultProfile,
  getProfilesByAgeGroup,
  getChildProfiles,
  getProfileAge,
  checkTimeRestrictions,
  getContentFilterLevel,
  canAccessContent,
  postgresProfileStore,
  // Subscriptions plugin
  createSubscriptionsPlugin,
  getSubscriptionsStore,
  createTier,
  getTierBySlug,
  getTierById,
  listTiers,
  getTierEntitlements,
  setTierEntitlements,
  getUserSubscription,
  createUserSubscription,
  updateUserSubscription,
  cancelSubscription,
  getUserTierSlug,
  getFeatureLimit,
  hasFeature,
  checkFeatureLimit,
  ensureUserSubscription,
  postgresSubscriptionsStore,
  // Usage plugin
  createUsagePlugin,
  getUsageStore,
  getDailyUsage,
  incrementUsage,
  checkUsageLimit,
  getFeatureUsageStatus,
  getDailyUsageSummary,
  resetUsage,
  getRemainingQuota,
  canUseFeature,
  postgresUsageStore,
  // Parental plugin
  createParentalPlugin,
  getParentalStore,
  getParentalAdapter,
  getGuardianSettings,
  createGuardianSettings,
  updateGuardianSettings,
  setPin,
  verifyPin,
  incrementFailedPinAttempts,
  resetFailedPinAttempts,
  getRestrictions,
  createRestriction,
  updateRestriction,
  deleteRestriction,
  pauseProfile,
  resumeProfile,
  checkProfileAccess,
  logActivity,
  getActivityLog,
  postgresParentalStore,
  kidsAdapter,
} from './plugins/index.js';
export type {
  HealthPluginConfig,
  LogsPluginConfig,
  ConfigPluginConfig,
  DiagnosticsPluginConfig,
  FrontendAppPluginConfig,
  // Postgres plugin types
  PostgresPluginConfig,
  PostgresInstance,
  TransactionCallback,
  // Cache plugin types
  CachePluginConfig,
  CacheInstance,
  // Auth plugin types
  AuthPluginConfig,
  AuthAdapter,
  AuthenticatedUser,
  AuthenticatedRequest,
  Auth0AdapterConfig,
  SupabaseAdapterConfig,
  BasicAdapterConfig,
  SupertokensAdapterConfig,
  AuthPluginState,
  AuthEnvPluginOptions,
  AuthConfigStatus,
  AuthConfigStore,
  PostgresAuthConfigStoreConfig,
  // Users plugin types
  UsersPluginConfig,
  UserStore,
  User,
  CreateUserInput,
  UpdateUserInput,
  UserSearchParams,
  UserListResponse,
  PostgresUserStoreConfig,
  UserSyncConfig,
  UsersApiConfig,
  UsersUiConfig,
  // Bans plugin types
  BansPluginConfig,
  BanStore,
  Ban,
  CreateBanInput,
  RemoveBanInput,
  BanCallbacks,
  PostgresBanStoreConfig,
  // Entitlements plugin types
  EntitlementsPluginConfig,
  EntitlementSource,
  EntitlementResult,
  EntitlementDefinition,
  EntitlementCallbacks,
  EntitlementsCacheConfig,
  EntitlementsApiConfig,
  PostgresEntitlementSourceConfig,
  UserEntitlement,
  CachedEntitlements,
  EntitlementStats,
  // Rate Limit plugin types
  RateLimitPluginConfig,
  RateLimitEnvPluginOptions,
  RateLimitStrategy,
  LimitStatus,
  StoredLimit,
  IncrementOptions,
  RateLimitStore,
  PostgresRateLimitStoreConfig,
  RateLimitCache,
  RateLimitCacheConfig,
  RateLimitMiddlewareOptions,
  // Devices plugin types
  Device,
  DeviceWithToken,
  CreateDeviceInput,
  UpdateDeviceInput,
  DeviceSearchParams,
  DeviceListResponse,
  TokenVerificationResult,
  DeviceAdapter,
  DeviceValidationResult,
  DeviceStore,
  DevicesPluginConfig,
  DevicesApiConfig,
  PostgresDeviceStoreConfig,
  ComputeDeviceMetadata,
  MobileDeviceMetadata,
  IoTDeviceMetadata,
  ComputeAdapterConfig,
  MobileAdapterConfig,
  DeviceTokenPair,
  // Profiles plugin types
  Profile,
  CreateProfileInput,
  UpdateProfileInput,
  ProfileSearchParams,
  ProfileListResponse,
  TimeRestrictionResult,
  ContentFilterLevel,
  AgeGroup,
  ProfileStore,
  ProfilesPluginConfig,
  ProfilesApiConfig,
  PostgresProfileStoreConfig,
  AgeThresholds,
  QwickBotProfileMetadata,
  GamingProfileMetadata,
  // Subscriptions plugin types
  SubscriptionTier,
  SubscriptionEntitlement,
  UserSubscription,
  UserSubscriptionWithTier,
  SubscriptionStatus,
  FeatureLimitResult,
  CreateTierInput,
  UpdateTierInput,
  CreateEntitlementInput,
  CreateUserSubscriptionInput,
  UpdateUserSubscriptionInput,
  SubscriptionsStore,
  SubscriptionsPluginConfig,
  SubscriptionsApiConfig,
  PostgresSubscriptionsStoreConfig,
  // Usage plugin types
  DailyUsage,
  MonthlyUsage,
  UsageIncrementResult,
  UsageStatus,
  UsageSummary,
  UsageStore,
  UsagePluginConfig,
  UsageApiConfig,
  UsageCleanupConfig,
  PostgresUsageStoreConfig,
  // Parental plugin types
  GuardianSettings,
  ProfileRestriction,
  ActivityLog,
  AccessCheckResult,
  CreateGuardianSettingsInput,
  UpdateGuardianSettingsInput,
  CreateRestrictionInput,
  LogActivityInput,
  ParentalAdapter,
  ParentalStore,
  ParentalPluginConfig,
  ParentalApiConfig,
  PostgresParentalStoreConfig,
  KidsAdapterConfig,
} from './plugins/index.js';
